language: python

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# Runs test suite
script:
  - python -m linkie.tests.run_tests

# Stop email notifications but post to organisation Slack channel
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
